### PR TITLE
feat: highlight invalid dates in preview

### PR DESCRIPTION
**Pull request by fkakatie**
## Description

- reinstate invalid date highlight in preview (when metadata publication date does not match date in pathname)

## Screenshots and Links

invalid date styling

invalid date: https://highlight-incorrect-date--blog--adobe.hlx3.page/en/drafts/katie/publish/2022/02/02/adobe-one-of-worlds-most-admired-companies
valid date: https://main--blog--adobe.hlx3.page/en/drafts/katie/publish/2022/02/02/how-young-chae-embraces-new-obstacles-as-an-opportunity-to-learn-and-grow

### CODE REVIEW

**Review by rofe — APPROVED** [review]
Cool! Maybe you could also add a title attribute with an explanation that authors would see when hovering over the invalid date element?

**Review by kptdobe — APPROVED** [review]

**Comment by rofe** [comment]
> @rofe I assume the title would need to come out of placeholders for localization. How should I handle all (every) language I don't speak? Just an English fallback for now?

Yes, fallback to English will be fine, we can let the team know that the message can be localized if desired. I can give you the German translation: _Ungültiges Datumsformat_ 🙂

**Comment by kptdobe** [comment]
Nit picking - the code does not really test the "format" but rather compare the date in Word and the one in the URL.

- `1-1-2022` in Word and `2022/1/1` in URL would pass while the "format" is not the expected one.
- `01-01-2022` in Word and `2022/01/1` in URL would fail while the Word date "format" is correct (here it is more a mismatch between the 2 dates / rename the folder).
Either we test the "format" and the error message can be `Invalid date format` or we detect "something wrong" but then the error message should rather be "Something is wrong with the dates"...

**Comment by fkakatie** [comment]
in ~978 years, we'll have to revisit the regex validation for year.

**Pull request merged**
