### PR TITLE
Load Milo variable when a block from its library gets loaded.

### PR DESCRIPTION
**Pull request by seanchoi-dev**
This PR goes with https://github.com/adobecom/milo/pull/53
- Getting variables.css from Milo CSS variables when Milo block gets loaded.

Related Ticket: [MWPW-111569](https://jira.corp.adobe.com/browse/MWPW-111569)

Current:
https://main--blog--adobe.hlx.page/en/drafts/seanchoi/milo-test

Test:
https://milo-variable--blog--adobe.hlx.page/en/drafts/seanchoi/milo-test

Note* this site seems outdated or hasn't synced up with bollerplate (https://github.com/adobe/helix-project-boilerplate/blob/main/scripts/scripts.js). Therefore, it doesn't work with block argument but it grabs `variables.css` from milo fine which is the purpose of this PR.

image

### CODE REVIEW

**Comment by fullcolorcoder** [comment]
@seanchoi-dev There are no test URLs

**Comment by seanchoi-dev** [comment]
> @seanchoi-dev There are no test URLs

I tried to create one but I think I have only view access for the blog. I can't find create doc button.
Can you grant me the access?
@fullcolorcoder

**Comment by fullcolorcoder** [comment]
@seanchoi-dev you'll have to get write access from the blog team.

**Comment by fullcolorcoder** [comment]
I am seeing a lot of breaking things though 

image

**Comment by amauch-adobe** [comment]
I gave Sean access to the blog site's sharepoint, he should be able to provide testing URLs now.

**Comment by seanchoi-dev** [comment]
> @seanchoi-dev I'm not 100% sure on shipping this until it's useful to the codebase. Perhaps we should consider updating the codebase first? Also the PSI is pretty low.

The variables.css is already merged in Milo side. So, this PR will only give benefit. And I think this PR shouldn't affect PSI score, so if it is low, it must be outdated scripts.js is the reason. In fact, this PR is more for syncing up with Milo Libs update not for specific request. I think there isn't a good reason to wait since the milo block css variables are missing in this site. (Not sure if they are used anywhere, yet but we want to fix before someone finds it, right?)

image

**Comment by fullcolorcoder** [comment]
@seanchoi-dev 
Just keeping a thread going here too for visibility:
- We should do a bug ticket just for this against blog onboarding 
- Remove duplicate variables / sort out any differences.

**Comment by amauch-adobe** [comment]
Hey Sean, I’m looking at your PR https://github.com/adobe/blog/pull/185 and I have tried this url to test it out:  https://milo-variable--blog--adobe.hlx.page/en/drafts/seanchoi/milo-test?milolibs=milo-variable, but I’m not seeing the columns fixes that were associated to MWPW-111569.

I also, just tried the straight test url you provided (without the milolibs url parameter), https://milo-variable--blog--adobe.hlx.page/en/drafts/seanchoi/milo-test, and it still doesn’t show the changes for MWPW-111569.  Am I supposed to just see that the variables.css is coming in from main.milo.pink for testing?  If that is the case, then yes I can see when using the testing URL above that you have provided that the variables.css file shows up in the network tab and is being pulled in from main.milo.pink.  That being said, if I use the test URL you provided with also the "?milolibs=milo-variable" parameter the variables.css file is no longer being requested and doesn't show up at all in the network tab.

So as far as I can say for my review, I did click the test URLs from the before vs. after and verified in the network tab for the "after test URL" the variables.css is being loaded successfully from main.milo.pink.

**Review by amauch-adobe — COMMENTED** [review]
See my comment above.

**Comment by seanchoi-dev** [comment]
Adding the response from Slack :
"So, what the PR does is grabbing variable.css from milo as milo block gets loaded.
You see the broken column block is because blog repo doesn't take argument as other helix site does. (See the note).

That must be handled with different ticket but Brad didn't want to approve (since he wants to be careful after the "incident") since it is looking broken. But really, merging the PR will give us only benefit not a risk in my point of view.

To fix the issue, though, we will need to sync up with boilerplate script into blog repo or at least to grab the part that adding argument class into the block element. I hope this makes sense to you.
I also will understand if you don't want to approve now.
I think I will work on this issue on Monday if I don't have anything else to do."

**Comment by seanchoi-dev** [comment]
> 

And it is merged, so the test page should looking good now.

**Review by amauch-adobe — COMMENTED** [review]
quick question, I just wanted to make sure I'm looking at this correctly.  When looking at both your test URLs after the PR #189 merge, I see that the columns now look correct for both the blog.adobe.com and milo.adobe.com, except for one thing that I wanted your comment on.  On the Milo test URL (the after URL), the second div of columns, the middle contained class column has a much larger margin on the left and right compared to the blog test URL (before URL).  This obviously could be just to the different styling between the two sites, but I wanted to make sure before giving my approval.  Also, where Brad had some questions I would also prefer to have his comments/approval on the PR before it is merged.  

That being said I have tested the before vs. after URLs on all browsers, platforms, and things are rendering fine according to the URLs provided.

**Comment by seanchoi-dev** [comment]
> quick question, I just wanted to make sure I'm looking at this correctly. When looking at both your test URLs after the PR #189 merge, I see that the columns now look correct for both the blog.adobe.com and milo.adobe.com, except for one thing that I wanted your comment on. On the Milo test URL (the after URL), the second div of columns, the middle contained class column has a much larger margin on the left and right compared to the blog test URL (before URL). This obviously could be just to the different styling between the two sites, but I wanted to make sure before giving my approval. Also, where Brad had some questions I would also prefer to have his comments/approval on the PR before it is merged.
> 
> That being said I have tested the before vs. after URLs on all browsers, platforms, and things are rendering fine according to the URLs provided.
> 
> See my screenshots below:
> 
> blog_before
> 
> milo_after

@amauch-adobe It is simply because blog doesn't have variable `--grid-container-width:  83.4%;` in their style while milo's does. So, that is correct change.

@fullcolorcoder Aaron is waiting your comment/approval.

**Review by fullcolorcoder — APPROVED** [review]

**Pull request merged**
